build:
	as -o add.o add.asm
	ld -o add add.o csc35.o
	as -o sub.o sub.asm
	ld -o sub sub.o csc35.o
	as -o inc.o inc.asm
	ld -o inc inc.o csc35.o
	as -o dec.o dec.asm
	ld -o dec dec.o csc35.o
	as -o mul.o mul.asm
	ld -o mul mul.o csc35.o
	as -o imul.o imul.asm
	ld -o imul imul.o csc35.o
	as -o div.o div.asm
	ld -o div div.o csc35.o
	as -o idiv.o idiv.asm
	ld -o idiv idiv.o csc35.o
clean:
	rm add.o
	rm add
	rm sub.o
	rm sub
	rm inc.o
	rm inc
	rm dec.o
	rm dec
	rm mul.o
	rm mul
	rm imul.o
	rm imul
	rm div.o
	rm div
	rm idiv.o
	rm idiv
